### ISSUE TITLE
NoMethodError (undefined method `functions' for #<Project:0x00007f87540a4ca8>):

### ISSUE THREAD

**Issue by xy74695321** [jbbarth/redmine_limited_visibility#3]

**Comment by xy74695321** [comment]
hi? author

**Comment by xy74695321** [comment]
Processing by IssuesController#index as HTML
  
Completed 500 Internal Server Error in 669ms (ActiveRecord: 33.8ms)

NoMethodError (undefined method `functions' for #<Project:0x00007f87540a4ca8>):
  plugins/redmine_limited_visibility/lib/redmine_limited_visibility/models/issue_query_patch.rb:29:in `initialize_available_filters'
  app/models/query.rb:596:in `available_filters'
  app/models/query.rb:373:in `build_from_params'
  app/models/issue_query.rb:77:in `build_from_params'
  app/helpers/queries_helper.rb:299:in `retrieve_query'
  plugins/redmine_limited_visibility/lib/redmine_limited_visibility/helpers/queries_helper_patch.rb:146:in `retrieve_query_with_limited_visibility'
  app/controllers/issues_controller.rb:43:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by xy74695321** [comment]
redmine3.4
